services:
  geth-node1:
    image: ethereum/client-go:latest
    container_name: geth-node1
    volumes:
      - ./node1_data:/data
      - ./password1.txt:/data/password.txt
    command: >
      --datadir=/data
      --networkid=1234
      --port=30301
      --http
      --http.port=8545
      --http.addr=0.0.0.0
      --http.api=eth,web3,net,admin,personal,miner,clique
      --http.corsdomain=*
      --mine
      --unlock=0x09206dbcf3804a72577d7bf96c66f78b147fc682
      --password=/data/password.txt
      --allow-insecure-unlock
    ports:
      - "8545:8545"
      - "30301:30301"

  geth-node2:
    image: ethereum/client-go:latest
    container_name: geth-node2
    volumes:
      - ./node2_data:/data
      - ./password2.txt:/data/password.txt
    command: >
      --datadir=/data
      --networkid=1234
      --port=30301
      --http
      --http.port=8545
      --http.addr=0.0.0.0
      --http.api=eth,web3,net,admin,personal,miner,clique
      --http.corsdomain=*
      --mine
      --unlock=0xf285d86346e74199ff2491bab5f3862363dd486a
      --password=/data/password.txt
      --allow-insecure-unlock
    ports:
      - "8546:8545"
      - "30302:30301"
    depends_on:
      - geth-node1
